### ISSUE TITLE
The cd command cannot switch directories (Interactive commands support)

### ISSUE THREAD

**Issue by HelloDB** [J-Rios/Arduino-esp32sshclient#2]
cd instructions cannot be executed, but other instructions are normal:
`ls` `ls -lh` `echo abc123 >> ~/esp32.log` `mkdir tmp` `ps -l` `env` `pip -V` ...

Failed instruction：
`cd` `cd ../` `cd tmp` `python` `ssh -V` ...

Do you know what caused this?
Sorry, my question is so much.:sweat_smile:

**Comment by J-Rios** [comment]
Just non-interactive commands are supported, no plans for support interactive stuffs.

The library behaviour for command execution is as follow:
  1 - Open a session and channel.
  2 - Send the command.
  3 - Get command response.
  4 - Close and free session and channel.

cd command is not working due to doesn't keep session.

**Comment by HelloDB** [comment]
I see that now,Thank you!
